# @yesassert (generate a standalone assert from a @type, even when unused) and
# @exportassert (export the generated helpers), plus the NAMESPACE writer.

test_that("@yesassert emits a standalone assert_type_<Name>()", {
  text <- "
    #' Shapes.
    #' @type Ack (data.table) one row:
    #' - id (character) the id.
    #' - n (numeric) a number.
    #' @yesassert
    #' @name shapes
    NULL
  "
  code <- proc_code(text)
  expect_true(any(grepl("^assert_type_Ack <- function\\(value\\) \\{", code)))
  expect_true(any(grepl("assert_data_table\\(value\\)", code)))
  expect_true(any(grepl('assert_has_columns\\(value, c\\("id", "n"\\)\\)', code)))
  expect_true(any(grepl("return\\(invisible\\(value\\)\\)", code)))
})

test_that("@yesassert emits a helper for every @type in the block", {
  text <- "
    #' Shapes.
    #' @type A (data.table) one row:
    #' - x (character) x.
    #' @type B (data.table) one row:
    #' - y (numeric) y.
    #' @yesassert
    #' @name shapes
    NULL
  "
  code <- proc_code(text)
  expect_true(any(grepl("^assert_type_A <- function", code)))
  expect_true(any(grepl("^assert_type_B <- function", code)))
})

test_that("@yesassert without a @type errors", {
  text <- "
    #' Oops.
    #' @yesassert
    #' @name oops
    NULL
  "
  expect_error(roxygen2::roc_proc_text(contract_roclet(), text), "@yesassert requires")
})

test_that("@exportassert records the generated type-assert names for export", {
  text <- "
    #' Shapes.
    #' @type Ack (data.table) one row:
    #' - id (character) the id.
    #' @yesassert
    #' @exportassert
    #' @name shapes
    NULL
  "
  res <- roxygen2::roc_proc_text(contract_roclet(), text)
  expect_true("assert_type_Ack" %in% res$exports)
})

test_that("@exportassert on a function exports its assert_args_/assert_return_", {
  text <- "
    #' Submit.
    #' @param x (scalar<character>) the id.
    #' @return (scalar<logical>) ok.
    #' @exportassert
    #' @export
    submit <- function(x) NULL
  "
  res <- roxygen2::roc_proc_text(contract_roclet(), text)
  expect_setequal(res$exports, c("assert_args_submit", "assert_return_submit"))
})

test_that("@exportassert on a block that generates no helper errors", {
  text <- "
    #' Plain.
    #' @param x untyped, skipped.
    #' @exportassert
    #' @export
    g <- function(x) NULL
  "
  expect_error(roxygen2::roc_proc_text(contract_roclet(), text), "no assert helper")
})

test_that(".ra_write_namespace_exports appends, is idempotent, and strips when empty", {
  dir <- file.path(tempdir(), "ra_ns_test")
  dir.create(dir, showWarnings = FALSE)
  on.exit(unlink(dir, recursive = TRUE), add = TRUE)
  ns <- file.path(dir, "NAMESPACE")
  writeLines(c("# Generated by roxygen2: do not edit by hand", "", "export(foo)"), ns)

  .ra_write_namespace_exports(dir, c("assert_type_Ack", "assert_args_foo"))
  out <- readLines(ns)
  expect_true(any(grepl("export(assert_type_Ack)", out, fixed = TRUE)))
  expect_true(any(grepl("export(assert_args_foo)", out, fixed = TRUE)))
  expect_true(any(grepl("export(foo)", out, fixed = TRUE))) # original untouched

  # Re-running replaces (not duplicates) the managed block.
  .ra_write_namespace_exports(dir, c("assert_type_Ack", "assert_args_foo"))
  expect_equal(sum(grepl("export(assert_type_Ack)", readLines(ns), fixed = TRUE)), 1L)

  # Empty removes the managed block, leaving the original directives.
  .ra_write_namespace_exports(dir, character())
  out2 <- readLines(ns)
  expect_false(any(grepl("assert_type_Ack", out2)))
  expect_false(any(grepl("managed", out2)))
  expect_true(any(grepl("export(foo)", out2, fixed = TRUE)))
})
