# @genassert (generate a standalone assert from a @type, even when unused) and
# @exportassert (export the generated helpers), plus the NAMESPACE writer.

test_that("@genassert emits a standalone assert_type_<Name>()", {
  text <- "
    #' Shapes.
    #' @type Ack (data.table) one row:
    #' - id (character) the id.
    #' - n (numeric) a number.
    #' @genassert
    #' @name shapes
    NULL
  "
  code <- proc_code(text)
  expect_true(any(grepl("^assert_type_Ack <- function\\(value\\) \\{", code)))
  expect_true(any(grepl("assert_data_table\\(value\\)", code)))
  expect_true(any(grepl('assert_has_columns\\(value, c\\("id", "n"\\)\\)', code)))
  expect_true(any(grepl("return\\(invisible\\(value\\)\\)", code)))
})

test_that("@genassert emits a helper for every @type in the block", {
  text <- "
    #' Shapes.
    #' @type A (data.table) one row:
    #' - x (character) x.
    #' @type B (data.table) one row:
    #' - y (numeric) y.
    #' @genassert
    #' @name shapes
    NULL
  "
  code <- proc_code(text)
  expect_true(any(grepl("^assert_type_A <- function", code)))
  expect_true(any(grepl("^assert_type_B <- function", code)))
})

test_that("@genassert without a @type errors", {
  text <- "
    #' Oops.
    #' @genassert
    #' @name oops
    NULL
  "
  expect_error(roxygen2::roc_proc_text(contract_roclet(), text), "@genassert requires")
})

test_that("@exportassert records the generated type-assert names for export", {
  text <- "
    #' Shapes.
    #' @type Ack (data.table) one row:
    #' - id (character) the id.
    #' @genassert
    #' @exportassert
    #' @name shapes
    NULL
  "
  res <- roxygen2::roc_proc_text(contract_roclet(), text)
  expect_true("assert_type_Ack" %in% res$exports)
})

test_that("@exportassert on a function exports its assert_args_/assert_return_", {
  text <- "
    #' Submit.
    #' @param x (scalar<character>) the id.
    #' @return (scalar<logical>) ok.
    #' @exportassert
    #' @export
    submit <- function(x) NULL
  "
  res <- roxygen2::roc_proc_text(contract_roclet(), text)
  expect_setequal(res$exports, c("assert_args_submit", "assert_return_submit"))
})

test_that("@exportassert on a block that generates no helper errors", {
  text <- "
    #' Plain.
    #' @param x untyped, skipped.
    #' @exportassert
    #' @export
    g <- function(x) NULL
  "
  expect_error(roxygen2::roc_proc_text(contract_roclet(), text), "no assert helper")
})

test_that(".ra_write_rd_exports writes a documenting Rd (not roxygen2-headed) and strips when empty", {
  dir <- file.path(tempdir(), "ra_rd_test")
  dir.create(file.path(dir, "man"), recursive = TRUE, showWarnings = FALSE)
  on.exit(unlink(dir, recursive = TRUE), add = TRUE)
  code <- c(
    "assert_type_OrderAck <- function(value) {",
    "  assert_data_table(value)",
    "}",
    "assert_args_submit <- function(symbol) {",
    "  assert_scalar_character(symbol)",
    "}"
  )
  rd <- file.path(dir, "man", "roxyassert-generated-asserts.Rd")

  .ra_write_rd_exports(dir, c("assert_type_OrderAck", "assert_args_submit"), code)
  expect_true(file.exists(rd))
  txt <- readLines(rd)
  expect_true(any(grepl("\\alias{assert_type_OrderAck}", txt, fixed = TRUE)))
  expect_true(any(grepl("\\alias{assert_args_submit}", txt, fixed = TRUE)))
  expect_true(any(grepl("assert_type_OrderAck(value)", txt, fixed = TRUE)))   # usage recovered
  expect_true(any(grepl("assert_args_submit(symbol)", txt, fixed = TRUE)))
  expect_true(any(grepl("\\keyword{internal}", txt, fixed = TRUE)))
  expect_false(any(grepl("Generated by roxygen2", txt)))                       # rd roclet won't purge it

  .ra_write_rd_exports(dir, character(), character())                          # empty removes it
  expect_false(file.exists(rd))
})

test_that(".ra_write_namespace_exports appends, is idempotent, and strips when empty", {
  dir <- file.path(tempdir(), "ra_ns_test")
  dir.create(dir, showWarnings = FALSE)
  on.exit(unlink(dir, recursive = TRUE), add = TRUE)
  ns <- file.path(dir, "NAMESPACE")
  writeLines(c("# Generated by roxygen2: do not edit by hand", "", "export(foo)"), ns)

  .ra_write_namespace_exports(dir, c("assert_type_Ack", "assert_args_foo"))
  out <- readLines(ns)
  expect_true(any(grepl("export(assert_type_Ack)", out, fixed = TRUE)))
  expect_true(any(grepl("export(assert_args_foo)", out, fixed = TRUE)))
  expect_true(any(grepl("export(foo)", out, fixed = TRUE))) # original untouched

  # Re-running replaces (not duplicates) the managed block.
  .ra_write_namespace_exports(dir, c("assert_type_Ack", "assert_args_foo"))
  expect_equal(sum(grepl("export(assert_type_Ack)", readLines(ns), fixed = TRUE)), 1L)

  # Empty removes the managed block, leaving the original directives.
  .ra_write_namespace_exports(dir, character())
  out2 <- readLines(ns)
  expect_false(any(grepl("assert_type_Ack", out2)))
  expect_false(any(grepl("managed", out2)))
  expect_true(any(grepl("export(foo)", out2, fixed = TRUE)))
})

test_that("the new tags are recognised (no unknown-tag warning) and reject stray args", {
  ok <- "
    #' Shapes.
    #' @type Ack (data.table) one row:
    #' - id (character) the id.
    #' @genassert
    #' @exportassert
    #' @name shapes
    NULL
  "
  expect_no_warning(roxygen2::roc_proc_text(contract_roclet(), ok))

  # @genassert / @exportassert are whole-block flags: a stray name list is an error.
  expect_error(roxygen2::roc_proc_text(contract_roclet(), "
    #' Shapes.
    #' @type Ack (data.table) one row:
    #' - id (character) the id.
    #' @genassert Ack
    #' @name shapes
    NULL
  "), "takes no arguments")
  expect_error(roxygen2::roc_proc_text(contract_roclet(), "
    #' Shapes.
    #' @type Ack (data.table) one row:
    #' - id (character) the id.
    #' @genassert
    #' @exportassert Ack
    #' @name shapes
    NULL
  "), "takes no arguments")
})

test_that("@exportassert on an on-disk R6 class exports its method asserts (7.x-faithful)", {
  dir <- withr::local_tempdir()
  dir.create(file.path(dir, "R"))
  writeLines(c(
    "Package: r6exp", "Title: t", "Version: 0.0.0", "Description: t.",
    "License: MIT + file LICENSE", "Encoding: UTF-8"
  ), file.path(dir, "DESCRIPTION"))
  writeLines(c(
    "#' @title Store",
    "#' @description A store.",
    "#' @exportassert",
    "Store <- R6::R6Class('Store',",
    "  public = list(",
    "    #' @description Get.",
    "    #' @param keys (character) keys.",
    "    #' @return (data.table) rows.",
    "    get = function(keys) NULL",
    "  )",
    ")"
  ), file.path(dir, "R", "Store.R"))
  blocks <- suppressMessages(roxygen2::parse_package(dir))
  results <- roxygen2::roclet_process(contract_roclet(), blocks, env = NULL, base_path = dir)
  expect_true("assert_args_Store__get" %in% results$exports)
  expect_true("assert_return_Store__get" %in% results$exports)
})

test_that("@genassert/@exportassert drive the on-disk roclet_output pipeline idempotently", {
  dir <- withr::local_tempdir()
  dir.create(file.path(dir, "R"))
  writeLines(c(
    "Package: ondisk", "Title: t", "Version: 0.0.0", "Description: t.",
    "License: MIT + file LICENSE", "Encoding: UTF-8"
  ), file.path(dir, "DESCRIPTION"))
  writeLines(c(
    "#' Shapes.",
    "#' @type Ack (data.table) one row:",
    "#' - id (character) the id.",
    "#' @genassert",
    "#' @exportassert",
    "#' @name shapes",
    "NULL"
  ), file.path(dir, "R", "shapes.R"))
  base_ns <- c("# Generated by roxygen2: do not edit by hand", "")
  rd <- file.path(dir, "man", "roxyassert-generated-asserts.Rd")

  run <- function() {
    writeLines(base_ns, file.path(dir, "NAMESPACE")) # mimic the namespace roclet
    blocks <- suppressMessages(roxygen2::parse_package(dir))
    results <- roxygen2::roclet_process(contract_roclet(), blocks, env = NULL, base_path = dir)
    roxygen2::roclet_output(contract_roclet(), results, base_path = dir)
  }

  run()
  ns1 <- readLines(file.path(dir, "NAMESPACE"))
  expect_true(any(grepl("export(assert_type_Ack)", ns1, fixed = TRUE)))
  expect_true(file.exists(rd))
  expect_true(any(grepl("\\alias{assert_type_Ack}", readLines(rd), fixed = TRUE)))
  rd1 <- readLines(rd)

  run() # second pass: NAMESPACE + Rd must be byte-identical
  expect_identical(readLines(file.path(dir, "NAMESPACE")), ns1)
  expect_identical(readLines(rd), rd1)
})
