# The roxyassert roclet: the roxygen2 integration point.
#
# At document() time it reads each block's typed @param / @return tags, parses
# the annotations (R/parse.R), lowers them to assert_*() calls (R/generate.R),
# and writes one helper per documented function into R/contracts-generated.R:
#   assert_args_<fn>(<args>)  — validates the inputs
#   assert_return_<fn>(value) — validates and returns the value
# You call these inside your function and commit the generated file.

#' roxyassert contract roclet
#'
#' Register this roclet in your package `DESCRIPTION` so `devtools::document()`
#' generates argument and return assertion helpers from your typed `@param` /
#' `@return` documentation:
#'
#' ```dcf
#' Roxygen: list(markdown = TRUE, roclets = c("collate", "namespace", "rd", "roxyassert::contract_roclet"))
#' ```
#'
#' The `roclets` list **replaces** roxygen2's default set rather than extending
#' it, so re-list `collate`, `namespace` and `rd` alongside this roclet. Dropping
#' `collate` is the dangerous slip: an `@include`-using package then stops having
#' its DESCRIPTION `Collate:` field maintained, and `R CMD INSTALL`/`R CMD check`
#' fails with `files in '.../R' missing from 'Collate' field` even though
#' `load_all()`/`test()` still pass locally.
#'
#' List this roclet **after** `"rd"`. Besides generating the contract helpers it
#' repairs the `man/*.Rd` that `rd` writes (so typed `@param`/`@return`
#' annotations render under markdown); that repair is a no-op unless `rd` has
#' already run.
#'
#' @return A roxygen2 roclet object.
#' @export
contract_roclet <- function() {
  return(roxygen2::roclet("contract"))
}

#' @exportS3Method roxygen2::roclet_process
roclet_process.roclet_contract <- function(x, blocks, env, base_path) {
  registry <- .ra_type_registry(blocks)
  code <- list()
  exports <- character()
  for (block in blocks) {
    res <- .ra_block_contract(block, registry)
    if (length(res$code) > 0L) {
      code[[length(code) + 1L]] <- res$code
    }
    exports <- c(exports, res$exports)
  }
  return(list(code = code, exports = unique(exports)))
}

#' @exportS3Method roxygen2::roclet_output
roclet_output.roclet_contract <- function(x, results, base_path, ...) {
  # Repair the man/*.Rd the `rd` roclet just wrote (it runs before us): markdown
  # mangles bare-word type fragments and a browser then hides them. See
  # .ra_repair_rd_types().
  .ra_repair_rd_types(base_path)

  path <- file.path(base_path, "R", "contracts-generated.R")
  code_results <- results$code
  exports <- if (is.null(results$exports)) character() else results$exports
  if (length(code_results) == 0L) {
    if (file.exists(path)) {
      file.remove(path)
    }
    # Drop any previously-managed export block / Rd when there is nothing to emit.
    .ra_write_namespace_exports(base_path, character())
    .ra_write_rd_exports(base_path, character(), character())
    return(invisible(character()))
  }
  banner <- c(
    "# Generated by roxyassert: do not edit by hand.",
    "# Re-generated on devtools::document(). Commit this file like NAMESPACE.",
    ""
  )
  body <- unlist(lapply(code_results, function(code) c(code, "")), use.names = FALSE)
  writeLines(c(banner, body), path)
  # Export the @exportassert-marked helpers: append a managed block to the package
  # NAMESPACE (the `namespace` roclet runs before us and rewrites it fresh, so
  # re-appending each run is deterministic), and write the Rd that documents them
  # (R requires exported objects to be documented).
  .ra_write_namespace_exports(base_path, exports)
  .ra_write_rd_exports(base_path, exports, body)
  return(path)
}

# When a package enables markdown, roxygen2 runs each @param / @return description
# through commonmark, which reads a bare-word fragment like `<POSIXct>` as raw
# inline HTML and lowers it to `\if{html}{\out{<POSIXct>}}`. That raw passthrough
# then renders as a phantom (unknown) HTML tag, so a browser silently drops it and
# the declared type shows as just `(scalar)`. A fragment that carries a space,
# comma, or bracket (`<numeric in ]0, Inf[>`, `<character, 1..>`) isn't tag-shaped,
# so commonmark leaves it as escaped text and it renders correctly — hence the
# visible inconsistency.
#
# We repair the *output*, not the input. roxygen2 applies markdown inside its own
# `roxy_tag_parse.roxy_tag_param`; that method CAN be overridden (it does dispatch),
# but doing so globally replaces @param parsing for every package documented while
# roxyassert is loaded — too invasive — so the contained choice is to rewrite the
# generated Rd: turn the mangled `\if{html}{\out{<Name>}}` back into a plain
# `<Name>`, which Rd escapes correctly across html/latex/text, identical to the
# fragments that were never mangled. (This roclet must run after `rd`, which writes
# the Rd — see the roclet's @description.)
#
# Scope. The rewrite fires only on a bare identifier `<[A-Za-z][A-Za-z0-9]*>` —
# exactly commonmark's tag-name shape (`[A-Za-z][A-Za-z0-9-]*`); a name with a
# `.`/`_`/space (`<data.table>`, `<numeric in ..>`) is never tag-shaped, so it is
# never mangled — glued, as a WHOLE word (the `\b`), to one of the grammar's outer
# category keywords: `scalar`, `class`, `promise`, `list` (keep in sync with the
# outer categories parsed in R/parse.R; `vector` is omitted because a vector is
# always `vector<T, len>` and the comma stops commonmark mangling it). The `\b`
# matters: without it the keyword would match as a *suffix* of a longer word
# (`subclass`, `blacklist`). This covers every emitted type fragment, including a
# nested `list<class<T>>` (the inner `<T>` follows `class`). The same shape in prose
# (`a list<Foo> note`) is also rewritten — there it likewise restores visible text
# instead of a browser-dropped tag, so it is never harmful — but a fragment NOT
# glued to a keyword (`foo<bar>`) and roxygen2's own structural tags (`\out{<hr>}`,
# `<div class=..>`, `</div>`) are left untouched. Known limitation: a real inline
# HTML tag written with no space after a keyword (`scalar<b>bold</b>`) would get its
# opening tag un-escaped while the closing tag survives; that input is not a type
# and is vanishingly unlikely, so it is left as-is.
.ra_rd_type_categories <- "scalar|class|promise|list"
.ra_rd_type_pattern <- paste0(
  "(\\b(?:",
  .ra_rd_type_categories,
  "))",
  "\\\\if\\{html\\}\\{\\\\out\\{(<[A-Za-z][A-Za-z0-9]*>)\\}\\}"
)

# A closed interval `[low, high]` is the second commonmark hazard in a type
# fragment. Where a bare `<tag>` is lowered to raw HTML (above), a `[..]` is read
# as a shortcut reference link and lowered to `\link{low, high}` — a dangling Rd
# cross-reference: it warns at document() time and renders as a broken link. Only
# the FULLY-closed form is mangled; every half-open form the grammar also accepts
# (`[1, Inf[`, `]0, 1]`, `]0, Inf[`) carries an unmatched bracket, so commonmark
# leaves it as text. We repair the output the same way: rewrite the generated
# `\link{low, high}` back to `[low, high]`. The body is constrained to an interval
# shape — a signed number or `Inf` on each side of the comma — which no real Rd
# link target (an R topic / `pkg::name`) can match, so a genuine `\link{}` is
# never disturbed; and a literal `[1, 2]` an author wrote in prose is restored to
# exactly that, which is what they meant.
.ra_rd_interval_bound <- "-?(?:\\d+(?:\\.\\d+)?|Inf)"
.ra_rd_interval_link_pattern <- paste0(
  "\\\\link\\{(",
  .ra_rd_interval_bound,
  "\\s*,\\s*",
  .ra_rd_interval_bound,
  ")\\}"
)

# Write a single Rd documenting every @exportassert-marked helper. R requires
# exported objects to be documented, so an undocumented export would trip an
# `R CMD check` WARNING. The file carries roxyassert's own banner (NOT roxygen2's),
# so the `rd` roclet -- which only purges Rd it generated itself -- leaves it
# alone. Hidden from the help index with \keyword{internal}; \usage is recovered
# from the generated definitions. An empty `exports` removes the file.
.ra_write_rd_exports <- function(base_path, exports, code) {
  rd <- file.path(base_path, "man", "roxyassert-generated-asserts.Rd")
  if (length(exports) == 0L) {
    if (file.exists(rd)) {
      file.remove(rd)
    }
    return(invisible(NULL))
  }
  man <- file.path(base_path, "man")
  if (!dir.exists(man)) {
    dir.create(man, recursive = TRUE)
  }
  exports <- sort(unique(exports))

  usages <- character()
  argnames <- character()
  for (nm in exports) {
    # Find the generated definition by a FIXED prefix (a helper name can contain
    # `.`, which would be a wildcard if interpolated into a regex), then extract
    # the args generically. Generated signatures never carry defaults, so a plain
    # comma split of the arg list is safe.
    prefix <- paste0(nm, " <- function(")
    line <- code[startsWith(code, prefix)]
    if (length(line) == 0L) {
      stop(sprintf("roxyassert: cannot recover the signature of exported helper '%s' for its Rd.", nm), call. = FALSE)
    }
    args <- sub("^[^(]*\\((.*)\\) \\{.*$", "\\1", line[[1]])
    usages <- c(usages, paste0(nm, "(", args, ")"))
    if (nzchar(args)) {
      parts <- trimws(strsplit(args, ",")[[1]])
      argnames <- c(argnames, parts[nzchar(parts)])
    }
  }
  argnames <- sort(unique(argnames))

  usage_lines <- character()
  for (i in seq_along(usages)) {
    usage_lines <- c(usage_lines, usages[[i]])
    if (i < length(usages)) {
      usage_lines <- c(usage_lines, "")
    }
  }

  lines <- c(
    "% Generated by roxyassert: do not edit by hand.",
    "\\name{roxyassert-generated-asserts}",
    "\\alias{roxyassert-generated-asserts}",
    sprintf("\\alias{%s}", exports),
    "\\title{Generated assertion helpers}",
    "\\usage{",
    usage_lines,
    "}"
  )
  if (length(argnames) > 0L) {
    items <- character()
    other <- setdiff(argnames, "value")
    if (length(other) > 0L) {
      items <- c(
        items,
        sprintf(
          "\\item{%s}{A function argument validated by the assert helper.}",
          paste(other, collapse = ", ")
        )
      )
    }
    if ("value" %in% argnames) {
      items <- c(items, "\\item{value}{The value or shaped object validated by the assert helper.}")
    }
    lines <- c(lines, "\\arguments{", items, "}")
  }
  lines <- c(
    lines,
    "\\value{",
    "\\code{assert_args_*} return \\code{invisible(NULL)}; \\code{assert_return_*}",
    "return the validated value; \\code{assert_type_*} return it invisibly. All are",
    "called for the side effect of signalling an error on a contract violation.",
    "}",
    "\\description{",
    "Runtime assertion helpers generated by roxyassert from typed roxygen",
    "documentation and exported via the \\verb{@exportassert} tag.",
    "}",
    "\\keyword{internal}"
  )
  writeLines(lines, rd)
  return(invisible(rd))
}

# Maintain a roxyassert-managed `export(...)` block at the tail of the package
# NAMESPACE for the @exportassert-marked helpers. The `namespace` roclet runs
# before us and rewrites NAMESPACE from scratch each document(), so the prior
# managed block is normally already gone; we strip any leftover and re-append,
# making the operation idempotent. Passing an empty `exports` removes the block.
.ra_write_namespace_exports <- function(base_path, exports) {
  exports <- sort(unique(exports))
  ns <- file.path(base_path, "NAMESPACE")
  if (!file.exists(ns)) {
    # The `namespace` roclet (which writes NAMESPACE) must run before us. If there
    # is nothing to export, quietly do nothing; if exports WERE requested, fail
    # loudly rather than silently drop them (and leave a documenting Rd dangling).
    if (length(exports) > 0L) {
      stop(
        paste0(
          "roxyassert: cannot export @exportassert helpers - no NAMESPACE found. ",
          "List the `namespace` roclet before `roxyassert::contract_roclet` in DESCRIPTION."
        ),
        call. = FALSE
      )
    }
    return(invisible(NULL))
  }
  begin <- "# roxyassert @exportassert: begin (managed - do not edit)"
  end <- "# roxyassert @exportassert: end (managed - do not edit)"
  lines <- readLines(ns, warn = FALSE)
  # Strip any prior managed block, tolerant of duplicated / out-of-order markers.
  b <- which(lines == begin)
  e <- which(lines == end)
  if (length(b) > 0L && length(e) > 0L) {
    lines <- lines[-(min(b):max(e))]
  }
  # Drop a trailing blank left by stripping the block, to avoid blank-line drift.
  while (length(lines) > 0L && !nzchar(lines[[length(lines)]])) {
    lines <- lines[-length(lines)]
  }
  if (length(exports) == 0L && length(lines) == 0L) {
    return(invisible(NULL)) # never write a 0-byte NAMESPACE
  }
  if (length(exports) > 0L) {
    block <- c(begin, sprintf("export(%s)", exports), end)
    # Separate from existing directives with one blank line - but only if there
    # ARE existing directives, so an otherwise-empty NAMESPACE gets no leading blank.
    lines <- if (length(lines) > 0L) c(lines, "", block) else block
  }
  writeLines(lines, ns)
  return(invisible(ns))
}

.ra_repair_rd_types <- function(base_path) {
  man <- file.path(base_path, "man")
  if (!dir.exists(man)) {
    return(invisible(character()))
  }
  repaired <- character()
  for (f in list.files(man, pattern = "\\.Rd$", full.names = TRUE)) {
    lines <- readLines(f, warn = FALSE, encoding = "UTF-8")
    fixed <- gsub(.ra_rd_type_pattern, "\\1\\2", lines, perl = TRUE)
    fixed <- gsub(.ra_rd_interval_link_pattern, "[\\1]", fixed, perl = TRUE)
    if (!identical(fixed, lines)) {
      writeLines(fixed, f, useBytes = TRUE)
      repaired <- c(repaired, f)
    }
  }
  return(invisible(repaired))
}

# ---- @type: reusable named types --------------------------------------------

#' @exportS3Method roxygen2::roxy_tag_parse
roxy_tag_parse.roxy_tag_type <- function(x) {
  x$val <- x$raw
  return(x)
}

# ---- @noassert: document a type without generating its check ----------------

#' @exportS3Method roxygen2::roxy_tag_parse
roxy_tag_parse.roxy_tag_noassert <- function(x) {
  x$val <- x$raw
  return(x)
}

# ---- @genassert / @exportassert ---------------------------------------------
#
# @genassert (on a block that defines one or more @type) emits a standalone,
# callable `assert_type_<Name>()` for EVERY @type in that block — useful for a
# type that no function references but whose shape you still want to validate
# (and export).
#
# @exportassert (on any block) exports the assert helpers generated FROM THAT
# block — the standalone `assert_type_*` of a @genassert block, and/or the
# `assert_args_*` / `assert_return_*` of a function or R6 method — so downstream
# packages can call them. Orthogonal to @genassert. Distinct from roxygen2's
# `@export`, which exports the documented object itself, not its assert helpers.
#
# Both are BARE, whole-block flags. They are deliberately NOT analogous to
# @noassert (which selects among one function's parameters with a name list): a
# @type is its own definition, so per-type control comes from block organisation
# — put a @type in its own block. A stray name list on these tags is therefore an
# error (see .ra_assert_bare_tag), not something silently ignored.

#' @exportS3Method roxygen2::roxy_tag_parse
roxy_tag_parse.roxy_tag_genassert <- function(x) {
  x$val <- x$raw
  return(x)
}

#' @exportS3Method roxygen2::roxy_tag_parse
roxy_tag_parse.roxy_tag_exportassert <- function(x) {
  x$val <- x$raw
  return(x)
}

# Assert a directive tag (@genassert / @exportassert) is bare. These are
# whole-block flags; per-type control comes from block organisation, so a stray
# name list is a mistake rather than something silently ignored.
.ra_assert_bare_tag <- function(block, tagname) {
  for (tag in roxygen2::block_get_tags(block, tagname)) {
    if (nzchar(trimws(.ra_tag_text(tag)))) {
      stop(
        sprintf(
          paste0(
            "roxyassert: @%s takes no arguments; it applies to the whole block. ",
            "For per-type control, put a @type in its own block."
          ),
          tagname
        ),
        call. = FALSE
      )
    }
  }
  return(invisible(NULL))
}

# Split a @noassert tag's text into the param names it exempts. A bare
# `@noassert` (no names) means the WHOLE function/method: the type still renders
# in the docs, but no check is generated. Returns list(all=, names=).
.ra_noassert_split <- function(text) {
  text <- trimws(text)
  if (nchar(text) == 0L) {
    return(list(all = TRUE, names = character()))
  }
  names <- strsplit(text, "[,[:space:]]+")[[1]]
  return(list(all = FALSE, names = names[nzchar(names)]))
}

# The @noassert directive for a plain-function block: list(all=, names=).
.ra_block_noassert <- function(block) {
  out <- list(all = FALSE, names = character())
  for (tag in roxygen2::block_get_tags(block, "noassert")) {
    no <- .ra_noassert_split(.ra_tag_text(tag))
    out$all <- out$all || no$all
    out$names <- c(out$names, no$names)
  }
  return(out)
}

# Drop the @noassert-exempted params from a param list (name/ast records), after
# verifying every exempted name actually IS a documented param of `where`.
.ra_apply_noassert <- function(params, names, where) {
  if (length(names) == 0L) {
    return(params)
  }
  have <- vapply(params, function(p) p$name, character(1))
  unknown <- setdiff(names, have)
  if (length(unknown) > 0L) {
    stop(
      "roxyassert: @noassert ",
      where,
      " names a parameter that is not documented: ",
      paste(unknown, collapse = ", "),
      call. = FALSE
    )
  }
  return(Filter(function(p) !(p$name %in% names), params))
}

# Collect every @type definition into a name -> type-node registry, so a bare
# name in an annotation can be resolved (inline) to its definition. Each
# definition is then resolved eagerly — references between @types are expanded
# (R/parse.R), so an unknown name or cycle is an error at document() time even
# when the @type is never used; the returned nodes are fully built-in.
.ra_type_registry <- function(blocks) {
  raw <- list()
  for (block in blocks) {
    for (tag in roxygen2::block_get_tags(block, "type")) {
      entry <- .ra_type_def(tag)
      if (!is.null(raw[[entry$name]])) {
        stop("roxyassert: duplicate @type '", entry$name, "'", call. = FALSE)
      }
      raw[[entry$name]] <- entry$node
    }
  }
  registry <- list()
  for (nm in names(raw)) {
    registry[[nm]] <- .ra_resolve_node(raw[[nm]], raw, nm)
  }
  return(registry)
}

# Parse one @type tag into list(name=, node=): a leading name then a single-type
# annotation. Errors on a missing name/type, a shadowed built-in, or a multi-
# alternative / nullable definition (those modifiers belong at the use site).
.ra_type_def <- function(tag) {
  raw <- .ra_tag_text(tag)
  m <- regmatches(raw, regexec("^\\s*([A-Za-z.][A-Za-z0-9._]*)\\s+([\\s\\S]*)$", raw, perl = TRUE))[[1]]
  if (length(m) != 3L) {
    stop("roxyassert: @type needs a name and a type, e.g. @type OrderAck (data.table)", call. = FALSE)
  }
  name <- m[[2]]
  if (name %in% .ra_type_reserved) {
    stop("roxyassert: @type cannot shadow the built-in type '", name, "'", call. = FALSE)
  }
  ast <- .ra_parse_or_stop(m[[3]], sprintf("@type '%s'", name))
  if (is.null(ast)) {
    stop("roxyassert: @type '", name, "' has no parseable (type)", call. = FALSE)
  }
  if (length(ast$alternatives) != 1L || isTRUE(ast$null_ok)) {
    stop(
      "roxyassert: @type '",
      name,
      "' must define a single type (no '|' union, '?' or '| NULL'; add those where you use it)",
      call. = FALSE
    )
  }
  return(list(name = name, node = ast$alternatives[[1]]))
}

# ---- per-block: build the helper(s) for one documented object ---------------

.ra_block_contract <- function(block, registry = list()) {
  # Standalone `assert_type_*` from @genassert (independent of the object kind),
  # then the function / R6-method helpers (the original behaviour).
  ty <- .ra_block_type_asserts(block, registry)
  fns <- if (inherits(block$object, "r6class")) {
    .ra_block_r6(block, registry)
  } else {
    .ra_block_fn(block, registry)
  }

  code <- ty$code
  if (length(fns$code) > 0L) {
    code <- c(if (length(code) > 0L) c(code, "") else code, fns$code)
  }
  nms <- c(ty$names, fns$names)

  exports <- character()
  if (.ra_block_has_tag(block, "exportassert")) {
    .ra_assert_bare_tag(block, "exportassert")
    if (length(nms) == 0L) {
      stop(
        paste0(
          "roxyassert: @exportassert on a block that generates no assert helper ",
          "(add @genassert to its @type, or typed @param/@return to a function)."
        ),
        call. = FALSE
      )
    }
    exports <- nms
  }
  return(list(code = code, exports = exports))
}

# The function/method helpers for one block. Returns list(code=, names=) where
# `names` are the generated helper names (for @exportassert). The plain-function
# path; the R6 path is .ra_block_r6().
.ra_block_fn <- function(block, registry) {
  fn <- .ra_block_name(block)
  if (is.null(fn)) {
    return(list(code = character(), names = character()))
  }
  no <- .ra_block_noassert(block)
  if (isTRUE(no$all)) {
    # Whole function is documented-only: emit no contract.
    return(list(code = character(), names = character()))
  }
  # Resolve (validate) every documented @param, then drop the @noassert ones from
  # code generation — their types are still validated and rendered, just not
  # enforced (a guard does that).
  params <- lapply(.ra_block_params(block), function(p) {
    p$ast <- .ra_resolve_or_stop(p$ast, registry, sprintf("@param '%s'", p$name))
    return(p)
  })
  params <- .ra_apply_noassert(params, no$names, sprintf("on %s()", fn))
  ret <- .ra_block_return(block)
  if (!is.null(ret)) {
    ret <- .ra_resolve_or_stop(ret, registry, "@return")
  }
  return(list(code = .ra_assemble(fn, params, ret), names = .ra_assemble_names(fn, params, ret)))
}

# Does the block carry at least one tag of this name?
.ra_block_has_tag <- function(block, name) {
  return(length(roxygen2::block_get_tags(block, name)) > 0L)
}

# For a block carrying @genassert, emit a standalone assert_type_<Name>() for
# every @type defined in that block. Returns list(code=, names=).
.ra_block_type_asserts <- function(block, registry) {
  if (!.ra_block_has_tag(block, "genassert")) {
    return(list(code = character(), names = character()))
  }
  .ra_assert_bare_tag(block, "genassert")
  type_tags <- roxygen2::block_get_tags(block, "type")
  if (length(type_tags) == 0L) {
    stop("roxyassert: @genassert requires at least one @type in the same block.", call. = FALSE)
  }
  code <- character()
  nms <- character()
  for (tag in type_tags) {
    # .ra_type_registry() already parsed this tag once (validating it and
    # emitting any deprecation warning); re-parsing here is only to recover the
    # name, so muffle warnings to keep it one warning per tag.
    name <- suppressWarnings(.ra_type_def(tag))$name
    helper <- .ra_build_type_helper(name, registry[[name]])
    code <- c(if (length(code) > 0L) c(code, "") else code, helper)
    nms <- c(nms, paste0("assert_type_", name))
  }
  return(list(code = code, names = nms))
}

# A standalone shape validator built from a resolved @type node.
.ra_build_type_helper <- function(name, node) {
  ast <- list(alternatives = list(node), null_ok = FALSE)
  body <- c(generate_checks(ast, "value"), "return(invisible(value))")
  return(c(
    sprintf("assert_type_%s <- function(value) {", name),
    paste0("  ", body),
    "}"
  ))
}

# Resolve a parsed annotation's named types against the registry, re-raising any
# error (unknown type, cycle) with the documentation location.
.ra_resolve_or_stop <- function(ast, registry, where) {
  return(tryCatch(.ra_resolve_slot(ast, registry), error = function(e) {
    stop("roxyassert: in ", where, ": ", conditionMessage(e), call. = FALSE)
  }))
}

# Stitch a function's annotated params + return into its helper code (shared by
# the plain-function and R6-method paths).
.ra_assemble <- function(fn, params, ret) {
  out <- character()
  if (length(params) > 0L) {
    out <- c(out, .ra_build_args_helper(fn, params))
  }
  if (!is.null(ret)) {
    if (length(out) > 0L) {
      out <- c(out, "")
    }
    out <- c(out, .ra_build_return_helper(fn, ret))
  }
  return(out)
}

# The helper names .ra_assemble() would emit for `fn` — mirrors its logic so a
# block can declare them for @exportassert without re-deriving the code.
.ra_assemble_names <- function(fn, params, ret) {
  nms <- character()
  if (length(params) > 0L) {
    nms <- c(nms, paste0("assert_args_", fn))
  }
  if (!is.null(ret)) {
    nms <- c(nms, paste0("assert_return_", fn))
  }
  return(nms)
}

# Parse one annotation, re-raising any error with the documentation location.
# After a successful parse, emit ONE deprecation warning per tag if any slot in
# the annotation used the type-side '?' null marker (rather than '| NULL') —
# the marker's position is now load-bearing (a '?' after a record field NAME
# means the key may be absent), so the value-level spelling is canonicalised.
# parse_annotation() itself stays warning-free: direct callers and tests parse
# without document()-time policy.
.ra_parse_or_stop <- function(text, where) {
  ast <- tryCatch(parse_annotation(text), error = function(e) {
    stop("roxyassert: in ", where, ": ", conditionMessage(e), call. = FALSE)
  })
  if (!is.null(ast) && .ra_slot_uses_question(ast)) {
    warning(
      "roxyassert: the type-side '?' null marker is deprecated; write '| NULL' instead (in ",
      where,
      "). A '?' after a record field NAME now means 'the key may be absent'.",
      call. = FALSE
    )
  }
  return(ast)
}

# Does any slot in this annotation AST carry the deprecated type-side '?' null
# marker? Checks the top slot, then recurses into every composite's field slots
# (a record's columns, to any depth) and, defensively, a list<T>'s element (a
# type node, which never carries a marker — but a nested composite's fields
# would).
.ra_slot_uses_question <- function(ast) {
  if (identical(ast$null_marker, "question")) {
    return(TRUE)
  }
  return(any(vapply(ast$alternatives, .ra_node_uses_question, logical(1))))
}

.ra_node_uses_question <- function(node) {
  if (!is.null(node$element) && .ra_node_uses_question(node$element)) {
    return(TRUE)
  }
  if (!is.null(node$fields)) {
    for (f in node$fields) {
      if (.ra_slot_uses_question(f$ast)) {
        return(TRUE)
      }
    }
  }
  return(FALSE)
}

# The documented object's name (a top-level function), or NULL to skip.
.ra_block_name <- function(block) {
  obj <- block$object
  if (is.null(obj) || !inherits(obj, "function")) {
    return(NULL)
  }
  return(obj$alias)
}

# Annotated @param tags, in documentation order, as a list of list(name=, ast=).
# A multi-name tag (`@param x,y ...`) applies its annotation to each name.
.ra_block_params <- function(block) {
  out <- list()
  for (tag in roxygen2::block_get_tags(block, "param")) {
    split <- .ra_param_split(tag)
    out <- .ra_add_param(out, split$names, split$text, sprintf("@param '%s'", split$names))
  }
  return(out)
}

# The annotation text of a tag, read from its PRISTINE `$raw` (roxygen2 rewrites
# `$val` through markdown when the package enables it, mangling our `<...>`
# syntax into `\if{html}{\out{<...>}}`; `$raw` is the untouched source).
#
# (Aside: with markdown on, roxygen2's RD link resolver also emits a harmless
# "could not resolve link" warning for the `[ ]` of an interval / a `[[ ]]`
# subscript in a description. That is purely the RD path; reading `$raw` here
# means our generation is unaffected. Documented in the README.)
.ra_tag_text <- function(tag) {
  if (!is.character(tag$raw)) {
    return("")
  }
  return(paste(tag$raw, collapse = "\n"))
}

# Split a @param's raw text into its (comma-separated) name list and annotation
# text. Read from $raw, NOT $val$name: when a user writes `@param a, b (...)`
# roxygen2 splits on the first space and mangles $val$name to "a,". The leading
# run of comma-separated identifiers is the names; the remainder is the text.
.ra_param_split <- function(tag) {
  raw <- .ra_tag_text(tag)
  pattern <- "^\\s*([A-Za-z0-9._]+(?:\\s*,\\s*[A-Za-z0-9._]+)*)\\s*([\\s\\S]*)$"
  m <- regmatches(raw, regexec(pattern, raw, perl = TRUE))[[1]]
  if (length(m) != 3L) {
    return(list(names = "", text = ""))
  }
  return(list(names = m[[2]], text = m[[3]]))
}

# Append a parsed @param (split across its comma-separated names) to a param list.
.ra_add_param <- function(out, names, description, where) {
  ast <- .ra_parse_or_stop(description, where)
  if (is.null(ast)) {
    return(out)
  }
  for (nm in strsplit(names, "\\s*,\\s*")[[1]]) {
    out[[length(out) + 1L]] <- list(name = nm, ast = ast)
  }
  return(out)
}

# The @return annotation AST, or NULL.
.ra_block_return <- function(block) {
  tag <- roxygen2::block_get_tag(block, "return")
  if (is.null(tag)) {
    return(NULL)
  }
  return(.ra_parse_or_stop(.ra_tag_text(tag), "@return"))
}

# ---- assemble the generated helpers -----------------------------------------

.ra_build_args_helper <- function(fn, params) {
  body <- character()
  for (p in params) {
    body <- c(body, generate_checks(p$ast, p$name))
  }
  body <- c(body, "return(invisible(NULL))")
  sig <- paste(vapply(params, function(p) p$name, character(1)), collapse = ", ")
  return(c(
    sprintf("assert_args_%s <- function(%s) {", fn, sig),
    paste0("  ", body),
    "}"
  ))
}

.ra_build_return_helper <- function(fn, ast) {
  body <- c(generate_checks(ast, "value"), "return(value)")
  return(c(
    sprintf("assert_return_%s <- function(value) {", fn),
    paste0("  ", body),
    "}"
  ))
}

# ---- R6 classes -------------------------------------------------------------
#
# roxygen2 collapses an R6 class's inline method docs into a single `r6class`
# block: each method's @param/@return tags live in `block$tags`, and `.r6data`
# (attached during parsing) records the methods and their source lines. We reuse
# roxygen2's own tag->method association so the split matches its RD output, then
# emit assert_args_<Class>__<method> / assert_return_<Class>__<method> per method.

.ra_block_r6 <- function(block, registry = list()) {
  r6 <- .ra_r6_data(block)
  if (is.null(r6)) {
    return(list(code = character(), names = character()))
  }
  methods <- r6$self[r6$self$type == "method", , drop = FALSE]
  if (nrow(methods) == 0L) {
    return(list(code = character(), names = character()))
  }

  class <- block$object$alias
  by_method <- .ra_r6_collect(block, methods)
  out <- character()
  nms <- character()
  for (method in names(by_method)) {
    info <- by_method[[method]]
    where <- sprintf("method %s()", method)
    params <- lapply(info$params, function(p) {
      p$ast <- .ra_resolve_or_stop(p$ast, registry, sprintf("@param '%s' of %s", p$name, where))
      return(p)
    })
    ret <- if (!is.null(info$ret)) .ra_resolve_or_stop(info$ret, registry, sprintf("@return of %s", where)) else NULL
    fn <- paste0(class, "__", method)
    code <- .ra_assemble(fn, params, ret)
    if (length(code) > 0L) {
      out <- c(if (length(out) > 0L) c(out, "") else out, code)
      nms <- c(nms, .ra_assemble_names(fn, params, ret))
    }
  }
  return(list(code = out, names = nms))
}

# Group the block's method-level @param/@return tags by method name, in source
# order, returning method -> list(params = list(list(name=, ast=)), ret = ast).
.ra_r6_collect <- function(block, methods) {
  find_method <- .ra_ns_fn("find_method_for_tag")
  by_method <- list()
  skips <- list() # method -> list(all=, names=), from @noassert
  for (tag in block$tags) {
    if (!(tag$tag %in% c("param", "return", "noassert")) || !.ra_r6_is_method_tag(tag, block)) {
      next
    }
    method <- if (!is.null(tag$r6method)) tag$r6method else find_method(methods, tag)
    # `method` is a single name, or NA/NULL/empty when the tag could not be
    # associated with one. Length-guard before is.na(): is.na(NULL) and
    # is.na(character(0)) are both logical(0), which would break the `if`.
    if (length(method) != 1L || is.na(method)) {
      next
    }
    if (is.null(by_method[[method]])) {
      by_method[[method]] <- list(params = list(), ret = NULL)
    }
    if (tag$tag == "param") {
      split <- .ra_param_split(tag)
      where <- sprintf("@param '%s' of method %s()", split$names, method)
      by_method[[method]]$params <- .ra_add_param(by_method[[method]]$params, split$names, split$text, where)
    } else if (tag$tag == "return") {
      by_method[[method]]$ret <- .ra_parse_or_stop(.ra_tag_text(tag), sprintf("@return of method %s()", method))
    } else {
      no <- .ra_noassert_split(.ra_tag_text(tag))
      if (is.null(skips[[method]])) {
        skips[[method]] <- list(all = FALSE, names = character())
      }
      skips[[method]]$all <- skips[[method]]$all || no$all
      skips[[method]]$names <- c(skips[[method]]$names, no$names)
    }
  }
  # Apply @noassert per method: a bare directive makes the whole method
  # documented-only; named params are dropped from its generated check.
  for (m in names(skips)) {
    if (isTRUE(skips[[m]]$all)) {
      by_method[[m]] <- list(params = list(), ret = NULL)
    } else {
      by_method[[m]]$params <- .ra_apply_noassert(
        by_method[[m]]$params,
        skips[[m]]$names,
        sprintf("of method %s()", m)
      )
    }
  }
  return(by_method)
}

# Does a @param / @return tag document an R6 *method* (rather than the class /
# constructor)? True when roxygen2 has already bound it to a method (`$r6method`)
# or it sits inline in the class body (at or below the class's definition line).
# This is roxygen2's own `r6_tag_type()` rule for these two tag kinds, computed
# directly from `tag$line` / `block$line` so we do not depend on that internal
# (it was added in roxygen2 8.0.0 and is absent in 7.x).
.ra_r6_is_method_tag <- function(tag, block) {
  if (!is.null(tag$r6method)) {
    return(TRUE)
  }
  # Without a binding, fall back to the positional rule. Treat any missing or
  # NA source line (on either the tag or the class) as "cannot tell" -> not a
  # method tag, rather than erroring. (`is.na(NULL)` is logical(0), which would
  # break the `if`, so the NULL checks must come first.)
  if (is.null(tag$line) || is.null(block$line) || is.na(tag$line) || is.na(block$line)) {
    return(FALSE)
  }
  return(tag$line >= block$line)
}

# The `.r6data` tag roxygen2 attaches to an R6 class block, or NULL.
.ra_r6_data <- function(block) {
  tag <- roxygen2::block_get_tag(block, ".r6data")
  if (is.null(tag)) {
    return(NULL)
  }
  return(tag$val)
}

# Fetch a roxygen2 internal needed for R6 tag association, with a clear error.
.ra_ns_fn <- function(name) {
  ns <- asNamespace("roxygen2")
  if (!exists(name, envir = ns, inherits = FALSE)) {
    stop(
      "roxyassert: R6 contract support needs roxygen2's internal '",
      name,
      "'; your roxygen2 version may be incompatible.",
      call. = FALSE
    )
  }
  return(get(name, envir = ns))
}
