# The roxyassert roclet: the roxygen2 integration point.
#
# At document() time it reads each block's typed @param / @return tags, parses
# the annotations (R/parse.R), lowers them to assert_*() calls (R/generate.R),
# and writes one helper per documented function into R/contracts-generated.R:
#   assert_args_<fn>(<args>)  — validates the inputs
#   assert_return_<fn>(value) — validates and returns the value
# You call these inside your function and commit the generated file.

#' roxyassert contract roclet
#'
#' Register this roclet in your package `DESCRIPTION` so `devtools::document()`
#' generates argument and return assertion helpers from your typed `@param` /
#' `@return` documentation:
#'
#' ```dcf
#' Roxygen: list(markdown = TRUE, roclets = c("namespace", "rd", "roxyassert::contract_roclet"))
#' ```
#'
#' @return A roxygen2 roclet object.
#' @export
contract_roclet <- function() {
  return(roxygen2::roclet("contract"))
}

#' @exportS3Method roxygen2::roclet_process
roclet_process.roclet_contract <- function(x, blocks, env, base_path) {
  registry <- .ra_type_registry(blocks)
  helpers <- list()
  for (block in blocks) {
    code <- .ra_block_contract(block, registry)
    if (length(code) > 0L) {
      helpers[[length(helpers) + 1L]] <- code
    }
  }
  return(helpers)
}

#' @exportS3Method roxygen2::roclet_output
roclet_output.roclet_contract <- function(x, results, base_path, ...) {
  # Repair the man/*.Rd the `rd` roclet just wrote (it runs before us): markdown
  # mangles bare-word type fragments and a browser then hides them. See
  # .ra_repair_rd_types().
  .ra_repair_rd_types(base_path)

  path <- file.path(base_path, "R", "contracts-generated.R")
  if (length(results) == 0L) {
    if (file.exists(path)) {
      file.remove(path)
    }
    return(invisible(character()))
  }
  banner <- c(
    "# Generated by roxyassert: do not edit by hand.",
    "# Re-generated on devtools::document(). Commit this file like NAMESPACE.",
    ""
  )
  body <- unlist(lapply(results, function(code) c(code, "")), use.names = FALSE)
  writeLines(c(banner, body), path)
  return(path)
}

# When a package enables markdown, roxygen2 runs each @param / @return description
# through commonmark, which reads a bare-word type fragment like `<POSIXct>` as raw
# inline HTML and lowers it to `\if{html}{\out{<POSIXct>}}`. That raw passthrough
# then renders as a phantom (unknown) HTML tag, so a browser silently drops it and
# the declared type shows as just `(scalar)`. Type fragments that carry a space,
# comma, or bracket (`<numeric in ]0, Inf[>`, `<character, 1..>`) don't look like a
# tag, so they survive as escaped text and render correctly — hence the visible
# inconsistency.
#
# We can't run before markdown (roxygen2 applies it inside its own
# `roxy_tag_parse.roxy_tag_param`, and R 3.6's S3 lookup finds the owner's own
# method before any external override), so instead we repair the *output*: rewrite
# the mangled `\if{html}{\out{<Name>}}` back to a plain `<Name>`, which Rd escapes
# correctly across html/latex/text — identical to the fragments that were never
# mangled.
#
# The rewrite is scoped so it only ever touches type fragments:
#   - the bracketed content must be a single bare identifier (`<POSIXct>`,
#     `<my.Class>`), never an attribute/closing/structural tag (`<div class=..>`,
#     `</div>`, `<a id=..>`), which carry spaces, `/`, or `=`; and
#   - it must be glued to a preceding non-space character — a type fragment always
#     follows its outer category (`scalar`, `class`, `promise`, ...) or a nesting
#     `<`, whereas roxygen2's R6 layout emits bare tags like `\out{<hr>}` on their
#     own line (whitespace-led), so a lookbehind for `\S` leaves those untouched.
.ra_rd_type_pattern <- "(?<=\\S)\\\\if\\{html\\}\\{\\\\out\\{(<[A-Za-z][A-Za-z0-9._]*>)\\}\\}"

.ra_repair_rd_types <- function(base_path) {
  man <- file.path(base_path, "man")
  if (!dir.exists(man)) {
    return(invisible(character()))
  }
  repaired <- character()
  for (f in list.files(man, pattern = "\\.Rd$", full.names = TRUE)) {
    lines <- readLines(f, warn = FALSE, encoding = "UTF-8")
    fixed <- gsub(.ra_rd_type_pattern, "\\1", lines, perl = TRUE)
    if (!identical(fixed, lines)) {
      writeLines(fixed, f, useBytes = TRUE)
      repaired <- c(repaired, f)
    }
  }
  return(invisible(repaired))
}

# ---- @type: reusable named types --------------------------------------------

#' @exportS3Method roxygen2::roxy_tag_parse
roxy_tag_parse.roxy_tag_type <- function(x) {
  x$val <- x$raw
  return(x)
}

# ---- @noassert: document a type without generating its check ----------------

#' @exportS3Method roxygen2::roxy_tag_parse
roxy_tag_parse.roxy_tag_noassert <- function(x) {
  x$val <- x$raw
  return(x)
}

# Split a @noassert tag's text into the param names it exempts. A bare
# `@noassert` (no names) means the WHOLE function/method: the type still renders
# in the docs, but no check is generated. Returns list(all=, names=).
.ra_noassert_split <- function(text) {
  text <- trimws(text)
  if (nchar(text) == 0L) {
    return(list(all = TRUE, names = character()))
  }
  names <- strsplit(text, "[,[:space:]]+")[[1]]
  return(list(all = FALSE, names = names[nzchar(names)]))
}

# The @noassert directive for a plain-function block: list(all=, names=).
.ra_block_noassert <- function(block) {
  out <- list(all = FALSE, names = character())
  for (tag in roxygen2::block_get_tags(block, "noassert")) {
    no <- .ra_noassert_split(.ra_tag_text(tag))
    out$all <- out$all || no$all
    out$names <- c(out$names, no$names)
  }
  return(out)
}

# Drop the @noassert-exempted params from a param list (name/ast records), after
# verifying every exempted name actually IS a documented param of `where`.
.ra_apply_noassert <- function(params, names, where) {
  if (length(names) == 0L) {
    return(params)
  }
  have <- vapply(params, function(p) p$name, character(1))
  unknown <- setdiff(names, have)
  if (length(unknown) > 0L) {
    stop(
      "roxyassert: @noassert ",
      where,
      " names a parameter that is not documented: ",
      paste(unknown, collapse = ", "),
      call. = FALSE
    )
  }
  return(Filter(function(p) !(p$name %in% names), params))
}

# Collect every @type definition into a name -> type-node registry, so a bare
# name in an annotation can be resolved (inline) to its definition. Each
# definition is then resolved eagerly — references between @types are expanded
# (R/parse.R), so an unknown name or cycle is an error at document() time even
# when the @type is never used; the returned nodes are fully built-in.
.ra_type_registry <- function(blocks) {
  raw <- list()
  for (block in blocks) {
    for (tag in roxygen2::block_get_tags(block, "type")) {
      entry <- .ra_type_def(tag)
      if (!is.null(raw[[entry$name]])) {
        stop("roxyassert: duplicate @type '", entry$name, "'", call. = FALSE)
      }
      raw[[entry$name]] <- entry$node
    }
  }
  registry <- list()
  for (nm in names(raw)) {
    registry[[nm]] <- .ra_resolve_node(raw[[nm]], raw, nm)
  }
  return(registry)
}

# Parse one @type tag into list(name=, node=): a leading name then a single-type
# annotation. Errors on a missing name/type, a shadowed built-in, or a multi-
# alternative / nullable definition (those modifiers belong at the use site).
.ra_type_def <- function(tag) {
  raw <- .ra_tag_text(tag)
  m <- regmatches(raw, regexec("^\\s*([A-Za-z.][A-Za-z0-9._]*)\\s+([\\s\\S]*)$", raw, perl = TRUE))[[1]]
  if (length(m) != 3L) {
    stop("roxyassert: @type needs a name and a type, e.g. @type OrderAck (data.table)", call. = FALSE)
  }
  name <- m[[2]]
  if (name %in% .ra_type_reserved) {
    stop("roxyassert: @type cannot shadow the built-in type '", name, "'", call. = FALSE)
  }
  ast <- .ra_parse_or_stop(m[[3]], sprintf("@type '%s'", name))
  if (is.null(ast)) {
    stop("roxyassert: @type '", name, "' has no parseable (type)", call. = FALSE)
  }
  if (length(ast$alternatives) != 1L || isTRUE(ast$null_ok)) {
    stop(
      "roxyassert: @type '",
      name,
      "' must define a single type (no '|' union, '?' or '| NULL'; add those where you use it)",
      call. = FALSE
    )
  }
  return(list(name = name, node = ast$alternatives[[1]]))
}

# ---- per-block: build the helper(s) for one documented object ---------------

.ra_block_contract <- function(block, registry = list()) {
  if (inherits(block$object, "r6class")) {
    return(.ra_block_r6(block, registry))
  }

  fn <- .ra_block_name(block)
  if (is.null(fn)) {
    return(character())
  }

  no <- .ra_block_noassert(block)
  if (isTRUE(no$all)) {
    # Whole function is documented-only: emit no contract.
    return(character())
  }

  # Resolve (validate) every documented @param, then drop the @noassert ones from
  # code generation — their types are still validated and rendered, just not
  # enforced (a guard does that).
  params <- lapply(.ra_block_params(block), function(p) {
    p$ast <- .ra_resolve_or_stop(p$ast, registry, sprintf("@param '%s'", p$name))
    return(p)
  })
  params <- .ra_apply_noassert(params, no$names, sprintf("on %s()", fn))
  ret <- .ra_block_return(block)
  if (!is.null(ret)) {
    ret <- .ra_resolve_or_stop(ret, registry, "@return")
  }
  return(.ra_assemble(fn, params, ret))
}

# Resolve a parsed annotation's named types against the registry, re-raising any
# error (unknown type, cycle) with the documentation location.
.ra_resolve_or_stop <- function(ast, registry, where) {
  return(tryCatch(.ra_resolve_slot(ast, registry), error = function(e) {
    stop("roxyassert: in ", where, ": ", conditionMessage(e), call. = FALSE)
  }))
}

# Stitch a function's annotated params + return into its helper code (shared by
# the plain-function and R6-method paths).
.ra_assemble <- function(fn, params, ret) {
  out <- character()
  if (length(params) > 0L) {
    out <- c(out, .ra_build_args_helper(fn, params))
  }
  if (!is.null(ret)) {
    if (length(out) > 0L) {
      out <- c(out, "")
    }
    out <- c(out, .ra_build_return_helper(fn, ret))
  }
  return(out)
}

# Parse one annotation, re-raising any error with the documentation location.
.ra_parse_or_stop <- function(text, where) {
  return(tryCatch(parse_annotation(text), error = function(e) {
    stop("roxyassert: in ", where, ": ", conditionMessage(e), call. = FALSE)
  }))
}

# The documented object's name (a top-level function), or NULL to skip.
.ra_block_name <- function(block) {
  obj <- block$object
  if (is.null(obj) || !inherits(obj, "function")) {
    return(NULL)
  }
  return(obj$alias)
}

# Annotated @param tags, in documentation order, as a list of list(name=, ast=).
# A multi-name tag (`@param x,y ...`) applies its annotation to each name.
.ra_block_params <- function(block) {
  out <- list()
  for (tag in roxygen2::block_get_tags(block, "param")) {
    split <- .ra_param_split(tag)
    out <- .ra_add_param(out, split$names, split$text, sprintf("@param '%s'", split$names))
  }
  return(out)
}

# The annotation text of a tag, read from its PRISTINE `$raw` (roxygen2 rewrites
# `$val` through markdown when the package enables it, mangling our `<...>`
# syntax into `\if{html}{\out{<...>}}`; `$raw` is the untouched source).
#
# (Aside: with markdown on, roxygen2's RD link resolver also emits a harmless
# "could not resolve link" warning for the `[ ]` of an interval / a `[[ ]]`
# subscript in a description. That is purely the RD path; reading `$raw` here
# means our generation is unaffected. Documented in the README.)
.ra_tag_text <- function(tag) {
  if (!is.character(tag$raw)) {
    return("")
  }
  return(paste(tag$raw, collapse = "\n"))
}

# Split a @param's raw text into its (comma-separated) name list and annotation
# text. Read from $raw, NOT $val$name: when a user writes `@param a, b (...)`
# roxygen2 splits on the first space and mangles $val$name to "a,". The leading
# run of comma-separated identifiers is the names; the remainder is the text.
.ra_param_split <- function(tag) {
  raw <- .ra_tag_text(tag)
  pattern <- "^\\s*([A-Za-z0-9._]+(?:\\s*,\\s*[A-Za-z0-9._]+)*)\\s*([\\s\\S]*)$"
  m <- regmatches(raw, regexec(pattern, raw, perl = TRUE))[[1]]
  if (length(m) != 3L) {
    return(list(names = "", text = ""))
  }
  return(list(names = m[[2]], text = m[[3]]))
}

# Append a parsed @param (split across its comma-separated names) to a param list.
.ra_add_param <- function(out, names, description, where) {
  ast <- .ra_parse_or_stop(description, where)
  if (is.null(ast)) {
    return(out)
  }
  for (nm in strsplit(names, "\\s*,\\s*")[[1]]) {
    out[[length(out) + 1L]] <- list(name = nm, ast = ast)
  }
  return(out)
}

# The @return annotation AST, or NULL.
.ra_block_return <- function(block) {
  tag <- roxygen2::block_get_tag(block, "return")
  if (is.null(tag)) {
    return(NULL)
  }
  return(.ra_parse_or_stop(.ra_tag_text(tag), "@return"))
}

# ---- assemble the generated helpers -----------------------------------------

.ra_build_args_helper <- function(fn, params) {
  body <- character()
  for (p in params) {
    body <- c(body, generate_checks(p$ast, p$name))
  }
  body <- c(body, "return(invisible(NULL))")
  sig <- paste(vapply(params, function(p) p$name, character(1)), collapse = ", ")
  return(c(
    sprintf("assert_args_%s <- function(%s) {", fn, sig),
    paste0("  ", body),
    "}"
  ))
}

.ra_build_return_helper <- function(fn, ast) {
  body <- c(generate_checks(ast, "value"), "return(value)")
  return(c(
    sprintf("assert_return_%s <- function(value) {", fn),
    paste0("  ", body),
    "}"
  ))
}

# ---- R6 classes -------------------------------------------------------------
#
# roxygen2 collapses an R6 class's inline method docs into a single `r6class`
# block: each method's @param/@return tags live in `block$tags`, and `.r6data`
# (attached during parsing) records the methods and their source lines. We reuse
# roxygen2's own tag->method association so the split matches its RD output, then
# emit assert_args_<Class>__<method> / assert_return_<Class>__<method> per method.

.ra_block_r6 <- function(block, registry = list()) {
  r6 <- .ra_r6_data(block)
  if (is.null(r6)) {
    return(character())
  }
  methods <- r6$self[r6$self$type == "method", , drop = FALSE]
  if (nrow(methods) == 0L) {
    return(character())
  }

  class <- block$object$alias
  by_method <- .ra_r6_collect(block, methods)
  out <- character()
  for (method in names(by_method)) {
    info <- by_method[[method]]
    where <- sprintf("method %s()", method)
    params <- lapply(info$params, function(p) {
      p$ast <- .ra_resolve_or_stop(p$ast, registry, sprintf("@param '%s' of %s", p$name, where))
      return(p)
    })
    ret <- if (!is.null(info$ret)) .ra_resolve_or_stop(info$ret, registry, sprintf("@return of %s", where)) else NULL
    code <- .ra_assemble(paste0(class, "__", method), params, ret)
    if (length(code) > 0L) {
      out <- c(if (length(out) > 0L) c(out, "") else out, code)
    }
  }
  return(out)
}

# Group the block's method-level @param/@return tags by method name, in source
# order, returning method -> list(params = list(list(name=, ast=)), ret = ast).
.ra_r6_collect <- function(block, methods) {
  find_method <- .ra_ns_fn("find_method_for_tag")
  by_method <- list()
  skips <- list() # method -> list(all=, names=), from @noassert
  for (tag in block$tags) {
    if (!(tag$tag %in% c("param", "return", "noassert")) || !.ra_r6_is_method_tag(tag, block)) {
      next
    }
    method <- if (!is.null(tag$r6method)) tag$r6method else find_method(methods, tag)
    # `method` is a single name, or NA/NULL/empty when the tag could not be
    # associated with one. Length-guard before is.na(): is.na(NULL) and
    # is.na(character(0)) are both logical(0), which would break the `if`.
    if (length(method) != 1L || is.na(method)) {
      next
    }
    if (is.null(by_method[[method]])) {
      by_method[[method]] <- list(params = list(), ret = NULL)
    }
    if (tag$tag == "param") {
      split <- .ra_param_split(tag)
      where <- sprintf("@param '%s' of method %s()", split$names, method)
      by_method[[method]]$params <- .ra_add_param(by_method[[method]]$params, split$names, split$text, where)
    } else if (tag$tag == "return") {
      by_method[[method]]$ret <- .ra_parse_or_stop(.ra_tag_text(tag), sprintf("@return of method %s()", method))
    } else {
      no <- .ra_noassert_split(.ra_tag_text(tag))
      if (is.null(skips[[method]])) {
        skips[[method]] <- list(all = FALSE, names = character())
      }
      skips[[method]]$all <- skips[[method]]$all || no$all
      skips[[method]]$names <- c(skips[[method]]$names, no$names)
    }
  }
  # Apply @noassert per method: a bare directive makes the whole method
  # documented-only; named params are dropped from its generated check.
  for (m in names(skips)) {
    if (isTRUE(skips[[m]]$all)) {
      by_method[[m]] <- list(params = list(), ret = NULL)
    } else {
      by_method[[m]]$params <- .ra_apply_noassert(
        by_method[[m]]$params,
        skips[[m]]$names,
        sprintf("of method %s()", m)
      )
    }
  }
  return(by_method)
}

# Does a @param / @return tag document an R6 *method* (rather than the class /
# constructor)? True when roxygen2 has already bound it to a method (`$r6method`)
# or it sits inline in the class body (at or below the class's definition line).
# This is roxygen2's own `r6_tag_type()` rule for these two tag kinds, computed
# directly from `tag$line` / `block$line` so we do not depend on that internal
# (it was added in roxygen2 8.0.0 and is absent in 7.x).
.ra_r6_is_method_tag <- function(tag, block) {
  if (!is.null(tag$r6method)) {
    return(TRUE)
  }
  # Without a binding, fall back to the positional rule. Treat any missing or
  # NA source line (on either the tag or the class) as "cannot tell" -> not a
  # method tag, rather than erroring. (`is.na(NULL)` is logical(0), which would
  # break the `if`, so the NULL checks must come first.)
  if (is.null(tag$line) || is.null(block$line) || is.na(tag$line) || is.na(block$line)) {
    return(FALSE)
  }
  return(tag$line >= block$line)
}

# The `.r6data` tag roxygen2 attaches to an R6 class block, or NULL.
.ra_r6_data <- function(block) {
  tag <- roxygen2::block_get_tag(block, ".r6data")
  if (is.null(tag)) {
    return(NULL)
  }
  return(tag$val)
}

# Fetch a roxygen2 internal needed for R6 tag association, with a clear error.
.ra_ns_fn <- function(name) {
  ns <- asNamespace("roxygen2")
  if (!exists(name, envir = ns, inherits = FALSE)) {
    stop(
      "roxyassert: R6 contract support needs roxygen2's internal '",
      name,
      "'; your roxygen2 version may be incompatible.",
      call. = FALSE
    )
  }
  return(get(name, envir = ns))
}
